export default employeeData = [
  {
    id: 1,
    name: "Shivam Dubey",
    billableHours: 5,
    nonBillableHours: 6,
  },
  {
    id: 2,
    name: "Shivam Dubey",
    billableHours: 5,
    nonBillableHours: 56,
  },
  {
    id: 3,
    name: "Shivam Dubey",
    billableHours: 25,
    nonBillableHours: 5,
  },
  {
    id: 4,
    name: "Shivam Dubey",
    billableHours: 5,
    nonBillableHours: 15,
  },
  {
    id: 5,
    name: "Shivam Dubey",
    billableHours: 8,
    nonBillableHours: 5,
  },
  {
    id: 6,
    name: "Shivam Dubey",
    billableHours: 2,
    nonBillableHours: 6,
  },
  {
    id: 7,
    name: "Shivam Dubey",
    billableHours: 5,
    nonBillableHours: 5,
  },
  {
    id: 8,
    name: "Shivam Dubey",
    billableHours: 5,
    nonBillableHours: 5,
  },
  {
    id: 9,
    name: "Shivam Dubey",
    billableHours: 5,
    nonBillableHours: 5,
  },
  {
    id: 10,
    name: "Shivam Dubey",
    billableHours: 5,
    nonBillableHours: 5,
  },
  {
    id: 11,
    name: "Shivam Dubey",
    billableHours: 5,
    nonBillableHours: 5,
  },
  {
    id: 12,
    name: "Shivam Dubey",
    billableHours: 5,
    nonBillableHours: 5,
  },
  {
    id: 13,
    name: "Shivam Dubey",
    billableHours: 5,
    nonBillableHours: 5,
  },
  {
    id: 14,
    name: "Shivam Dubey",
    billableHours: 5,
    nonBillableHours: 5,
  },
  {
    id: 15,
    name: "Shivam Dubey",
    billableHours: 5,
    nonBillableHours: 5,
  },
  {
    id: 16,
    name: "Shivam Dubey",
    billableHours: 5,
    nonBillableHours: 5,
  },
  {
    id: 17,
    name: "Shivam Dubey",
    billableHours: 5,
    nonBillableHours: 5,
  },
  {
    id: 18,
    name: "Shivam Dubey",
    billableHours: 5,
    nonBillableHours: 5,
  },
  {
    id: 19,
    name: "Shivam Dubey",
    billableHours: 5,
    nonBillableHours: 5,
  },
  {
    id: 20,
    name: "Shivam Dubey",
    billableHours: 5,
    nonBillableHours: 5,
  },
];
